# Generated by Django 3.1.7 on 2021-05-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(blank=True, default='No registrado', max_length=255)),
                ('ubicacion', models.CharField(blank=True, default='No registrado', max_length=255)),
                ('clima', models.CharField(blank=True, default='No registrado', max_length=255)),
                ('temp_Ext', models.FloatField(blank=True, default=0)),
                ('temp_int', models.FloatField(blank=True, default=0)),
                ('humedad_int', models.FloatField(blank=True, default=0)),
                ('peso_colmena', models.FloatField(blank=True, default=0)),
                ('poblacion', models.FloatField(blank=True, default=0)),
                ('comida', models.FloatField(blank=True, default=0)),
                ('piquera_abierta', models.CharField(blank=True, default='Cerrada', max_length=255)),
                ('reina_dentro', models.CharField(blank=True, default='Adentro', max_length=255)),
                ('revision', models.CharField(blank=True, default='No revisado', max_length=255)),
            ],
        ),
    ]
