# Generated by Django 3.1.7 on 2021-07-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restbee_app', '0002_auto_20210510_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='No_revisado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(blank=True, default='No registrado', max_length=255)),
                ('ubicacion', models.CharField(blank=True, default='No registrado', max_length=255)),
                ('temp_int', models.FloatField(blank=True, default=0)),
            ],
        ),
    ]
