# Generated by Django 3.1.7 on 2021-10-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restbee_app', '0003_no_revisado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_data',
            old_name='humedad_int',
            new_name='humedad',
        ),
        migrations.RenameField(
            model_name='add_data',
            old_name='ubicacion',
            new_name='local',
        ),
        migrations.RenameField(
            model_name='add_data',
            old_name='peso_colmena',
            new_name='peso',
        ),
        migrations.RenameField(
            model_name='add_data',
            old_name='poblacion',
            new_name='t_Ext',
        ),
        migrations.RenameField(
            model_name='add_data',
            old_name='temp_Ext',
            new_name='t_int',
        ),
        migrations.RenameField(
            model_name='no_revisado',
            old_name='ubicacion',
            new_name='local',
        ),
        migrations.RenameField(
            model_name='no_revisado',
            old_name='temp_int',
            new_name='t_int',
        ),
        migrations.RemoveField(
            model_name='add_data',
            name='reina',
        ),
        migrations.RemoveField(
            model_name='add_data',
            name='temp_int',
        ),
        migrations.AlterField(
            model_name='add_data',
            name='revision',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
