# Generated by Django 3.1.7 on 2021-10-08 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restbee_app', '0005_errors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(blank=True, default='No registrado', max_length=255)),
            ],
            options={
                'verbose_name': 'Datos',
                'verbose_name_plural': 'Revisiones',
            },
        ),
        migrations.AlterModelOptions(
            name='add_data',
            options={'verbose_name': 'Datos', 'verbose_name_plural': 'Colmenas_supervisadas'},
        ),
        migrations.AlterModelOptions(
            name='errors',
            options={'verbose_name': 'Errores', 'verbose_name_plural': 'Historial_de_errores'},
        ),
        migrations.AlterModelOptions(
            name='no_revisado',
            options={'verbose_name': 'Datos', 'verbose_name_plural': 'Colmenas_no_supervisadas'},
        ),
        migrations.RenameField(
            model_name='add_data',
            old_name='t_Ext',
            new_name='t_ext',
        ),
        migrations.RemoveField(
            model_name='add_data',
            name='revision',
        ),
        migrations.AddField(
            model_name='add_data',
            name='id_revision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restbee_app.revision'),
        ),
    ]
